/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World! This is Neo"
        }
}

fun main() {
    println(App().greeting)
}

